Shell: Shell.o Parse.o Execute.o
		cc -o Shell Shell.o Parse.o Execute.o
Shell.o: Shell.c
		cc -c Shell.c
Parse.o: Parse.c
		cc -c Parse.c
Execute.o: Execute.c
		cc -c Execute.c
clean:
		rm Shell Shell.o Parse.o Execute.o